#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

set -xe

bold=$(jq -r .bold config.json)
bold_events=$(jq -r .bold_events config.json)
events=$(jq -r .events config.json)

python main.py $bold $bold_events "$events"
